apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
spec:
  securityContext:
    # runAsNonRoot: false
    runAsUser: 101
    # runAsGroup: 1000
    # fsGroup: 3000
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    resources:
      limits:
        memory: "256Mi"
        cpu: "100m"
      requests:
        memory: "256Mi"
        cpu: "100m"

